services:
  db:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pg-network
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - pg-network
    ports:
      - "8080:80"
    volumes:
      - ./.pgadmin:/var/lib/pgadmin:rw
networks:
  pg-network:
    name: pg-network
volumes:
  .db:
  .pgadmin:
